Repository Zillacracy-org/ssibrowser.com, pull requests merged in 2021-06, with the labels that each got.

#13 [Issue-12] Pre commit - Husky
  .eslintrc.js
  .husky/.gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc.js
  .vscode/settings.json
  package-lock.json
  package.json
Labels: enhancement, tier1

#18 DID Address
  package-lock.json
  package.json
  src/App.tsx
  src/components/Contact/index.tsx
  src/components/SearchBar/index.tsx
  src/components/SearchBar/styles.module.scss
  src/components/SearchBar/utils.ts
  src/constants/routes.ts
Labels: tier1

#20 fix some vulnerabilities
  package-lock.json
  package.json
  yarn.lock
Labels: tier2

#21 Resolve domain name NFT into its DID Document
  src/components/SearchBar/index.tsx
  src/components/SearchBar/utils.ts
Labels: tier1
